// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPlayer = `-- name: CreatePlayer :one
insert into player (name, age, rating)
values ($1, $2, 0)
returning id
`

type CreatePlayerParams struct {
	Name string
	Age  int16
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPlayer, arg.Name, arg.Age)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAllPlayers = `-- name: GetAllPlayers :many
select id, name, age, rating from player
`

func (q *Queries) GetAllPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.Query(ctx, getAllPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerById = `-- name: GetPlayerById :one
select id, name, age, rating from player where id = $1
`

func (q *Queries) GetPlayerById(ctx context.Context, id uuid.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerById, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Age,
		&i.Rating,
	)
	return i, err
}

const updatePlayerRating = `-- name: UpdatePlayerRating :one
update player
   set rating = $2
 where id = $1
returning rating
`

type UpdatePlayerRatingParams struct {
	ID     uuid.UUID
	Rating int32
}

func (q *Queries) UpdatePlayerRating(ctx context.Context, arg UpdatePlayerRatingParams) (int32, error) {
	row := q.db.QueryRow(ctx, updatePlayerRating, arg.ID, arg.Rating)
	var rating int32
	err := row.Scan(&rating)
	return rating, err
}
