// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: players/v1/players.proto

package players

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerService) Reset() {
	*x = PlayerService{}
	mi := &file_players_v1_players_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerService) ProtoMessage() {}

func (x *PlayerService) ProtoReflect() protoreflect.Message {
	mi := &file_players_v1_players_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerService.ProtoReflect.Descriptor instead.
func (*PlayerService) Descriptor() ([]byte, []int) {
	return file_players_v1_players_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerService) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerService) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *PlayerService) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type CreatePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerRequest) Reset() {
	*x = CreatePlayerRequest{}
	mi := &file_players_v1_players_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerRequest) ProtoMessage() {}

func (x *CreatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_players_v1_players_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_players_v1_players_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePlayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlayerRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type CreatePlayerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerReply) Reset() {
	*x = CreatePlayerReply{}
	mi := &file_players_v1_players_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerReply) ProtoMessage() {}

func (x *CreatePlayerReply) ProtoReflect() protoreflect.Message {
	mi := &file_players_v1_players_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerReply.ProtoReflect.Descriptor instead.
func (*CreatePlayerReply) Descriptor() ([]byte, []int) {
	return file_players_v1_players_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePlayerReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_players_v1_players_proto protoreflect.FileDescriptor

const file_players_v1_players_proto_rawDesc = "" +
	"\n" +
	"\x18players/v1/players.proto\"]\n" +
	"\rPlayerService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\";\n" +
	"\x13CreatePlayerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\"#\n" +
	"\x11CreatePlayerReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2E\n" +
	"\aPlayers\x12:\n" +
	"\fCreatePlayer\x12\x14.CreatePlayerRequest\x1a\x12.CreatePlayerReply\"\x00B\fZ\n" +
	"./;playersb\x06proto3"

var (
	file_players_v1_players_proto_rawDescOnce sync.Once
	file_players_v1_players_proto_rawDescData []byte
)

func file_players_v1_players_proto_rawDescGZIP() []byte {
	file_players_v1_players_proto_rawDescOnce.Do(func() {
		file_players_v1_players_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_players_v1_players_proto_rawDesc), len(file_players_v1_players_proto_rawDesc)))
	})
	return file_players_v1_players_proto_rawDescData
}

var file_players_v1_players_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_players_v1_players_proto_goTypes = []any{
	(*PlayerService)(nil),       // 0: PlayerService
	(*CreatePlayerRequest)(nil), // 1: CreatePlayerRequest
	(*CreatePlayerReply)(nil),   // 2: CreatePlayerReply
}
var file_players_v1_players_proto_depIdxs = []int32{
	1, // 0: Players.CreatePlayer:input_type -> CreatePlayerRequest
	2, // 1: Players.CreatePlayer:output_type -> CreatePlayerReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_players_v1_players_proto_init() }
func file_players_v1_players_proto_init() {
	if File_players_v1_players_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_players_v1_players_proto_rawDesc), len(file_players_v1_players_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_players_v1_players_proto_goTypes,
		DependencyIndexes: file_players_v1_players_proto_depIdxs,
		MessageInfos:      file_players_v1_players_proto_msgTypes,
	}.Build()
	File_players_v1_players_proto = out.File
	file_players_v1_players_proto_goTypes = nil
	file_players_v1_players_proto_depIdxs = nil
}
