#build stage
FROM golang:1.24.1-alpine3.21 AS builder
ARG SERVICE_NAME

WORKDIR /micro-durak/$SERVICE_NAME

COPY ./cmd ./cmd
COPY ./services ./services
COPY ./lib ./lib
COPY ./database ./database
COPY ./go.mod ./go.sum ./

RUN go build -o app ./cmd/$SERVICE_NAME/main.go

#final stage
FROM alpine:3.21
ARG SERVICE_NAME

WORKDIR /root/

COPY --from=builder /micro-durak/$SERVICE_NAME/app ./

CMD ["./app"]

EXPOSE 8080
