# k8s/services/game-manager.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-manager
  template:
    metadata:
      labels:
        app: game-manager
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do sleep 2; done']
      containers:
        - name: game-manager
          imagePullPolicy: Always
          image: ghcr.io/momuswinner/game-manager:main
          ports:
            - containerPort: 7070
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_URL

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            - name: REDIS_URL
              value: "redis://:$(REDIS_PASSWORD)@redis:6379/0"

            - name: PLAYERS_URL
              value: "players:9090"

            - name: JWT_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_PUBLIC
---
apiVersion: v1
kind: Service
metadata:
  name: game-manager
spec:
  selector:
    app: game-manager
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
