apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaker
  template:
    metadata:
      labels:
        app: matchmaker
    spec:
      initContainers:
        - name: wait-for-redis
          image: redis:7.4-alpine3.21
          command: ['sh', '-c', 'until redis-cli -h redis -p 6379 -a $REDIS_PASSWORD ping | grep PONG; do sleep 2; done']
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
        
        - name: wait-for-players
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z players 9090; do sleep 2; done']
      
      containers:
        - name: matchmaker
          imagePullPolicy: Always
          image: ghcr.io/momuswinner/matchmaker:main
          ports:
            - containerPort: 8080
          env:
            - name: JWT_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_PUBLIC
            
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            - name: REDIS_URL
              value: "redis://:$(REDIS_PASSWORD)@redis:6379/0"
            
            - name: PLAYERS_URL
              value: "players:9090"
            - name: GAME_URL
              value: "game:9090"
---
apiVersion: v1
kind: Service
metadata:
  name: matchmaker
spec:
  selector:
    app: matchmaker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

