apiVersion: apps/v1
kind: Deployment
metadata:
  name: players
spec:
  replicas: 1
  selector:
    matchLabels:
      app: players
  template:
    metadata:
      labels:
        app: players
    spec:
      initContainers:
        - name: wait-for-database
          image: postgres:17.4-alpine3.21
          command: ["sh", "-c", "until pg_isready -h database -p 5432; do sleep 2; done"]
      containers:
        - name: players
          imagePullPolicy: Always
          image: ghcr.io/momuswinner/players:main
          env:
          - name: GRPC_PORT
            value: "9090"
          - name: JWT_PUBLIC
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_PUBLIC
      
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: DB_URI
          ports:
          - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: players
spec:
  selector:
    app: players
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090
      protocol: TCP
