// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: game/v1/games.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_game_v1_games_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_games_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_games_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_game_v1_games_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_games_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_game_v1_games_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

var File_game_v1_games_proto protoreflect.FileDescriptor

const file_game_v1_games_proto_rawDesc = "" +
	"\n" +
	"\x13game/v1/games.proto\".\n" +
	"\x11CreateGameRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"-\n" +
	"\x12CreateGameResponse\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId2?\n" +
	"\x04Game\x127\n" +
	"\n" +
	"CreateGame\x12\x12.CreateGameRequest\x1a\x13.CreateGameResponse\"\x00B\tZ\a./;gameb\x06proto3"

var (
	file_game_v1_games_proto_rawDescOnce sync.Once
	file_game_v1_games_proto_rawDescData []byte
)

func file_game_v1_games_proto_rawDescGZIP() []byte {
	file_game_v1_games_proto_rawDescOnce.Do(func() {
		file_game_v1_games_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_v1_games_proto_rawDesc), len(file_game_v1_games_proto_rawDesc)))
	})
	return file_game_v1_games_proto_rawDescData
}

var file_game_v1_games_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_game_v1_games_proto_goTypes = []any{
	(*CreateGameRequest)(nil),  // 0: CreateGameRequest
	(*CreateGameResponse)(nil), // 1: CreateGameResponse
}
var file_game_v1_games_proto_depIdxs = []int32{
	0, // 0: Game.CreateGame:input_type -> CreateGameRequest
	1, // 1: Game.CreateGame:output_type -> CreateGameResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_v1_games_proto_init() }
func file_game_v1_games_proto_init() {
	if File_game_v1_games_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_v1_games_proto_rawDesc), len(file_game_v1_games_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_v1_games_proto_goTypes,
		DependencyIndexes: file_game_v1_games_proto_depIdxs,
		MessageInfos:      file_game_v1_games_proto_msgTypes,
	}.Build()
	File_game_v1_games_proto = out.File
	file_game_v1_games_proto_goTypes = nil
	file_game_v1_games_proto_depIdxs = nil
}
