// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MatchResult struct {
	ID          pgtype.UUID
	PlayerCount int16
}

type Player struct {
	ID     pgtype.UUID
	Name   string
	Age    int16
	Rating int32
}

type PlayerAuth struct {
	ID       pgtype.UUID
	PlayerID pgtype.UUID
	Email    string
	Password string
}

type PlayerPlacement struct {
	MatchResultID pgtype.UUID
	PlayerID      pgtype.UUID
	PlayerPlace   int16
	RankChange    int32
}
